version: '3.8'

services:
  bot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "npm install && npm run dev"
